"use client";
import { useEffect, useState } from "react";
import { Ctx, setIn, F, Chk, Sel, Media, List } from "./ui";
const TABS = ["Dashboard", "Profile & Branding", "Home / Hero", "Intro Video", "Services", "Portfolio", "Reviews", "Contact", "Social Links", "Footer", "Site Settings"];
const CATS = ["Educational", "Brand Ads", "Cinematic", "YouTube", "Instagram Reels", "Shorts", "Podcast", "Commercial", "Other"];
export default function Admin() {
  const [c, setC] = useState<any>(null); const [auth, setAuth] = useState<boolean | null>(null); const [tab, setTab] = useState(0); const [pw, setPw] = useState("");
  const [t, setT] = useState<any>(null); const [busy, setBusy] = useState(false); const [rv, setRv] = useState<any>({ reviews: [], count: 0, average: 0 }); const [msgs, setMsgs] = useState<any[]>([]);
  const toast = (m: string, e = false) => { setT({ m, e }); setTimeout(() => setT(null), 3500); };
  const set = (p: string, v: any) => setC((x: any) => setIn(x, p.split("."), v));
  const load = async () => { const r = await fetch("/api/admin/content"); if (!r.ok) return setAuth(false); setC(await r.json()); setAuth(true);
    const a = await fetch("/api/admin/reviews"); if (a.ok) setRv(await a.json()); const m = await fetch("/api/contact"); if (m.ok) setMsgs(await m.json()); };
  useEffect(() => { load(); }, []);
  async function login(e: React.FormEvent) { e.preventDefault(); const r = await fetch("/api/admin/login", { method: "POST", body: JSON.stringify({ password: pw }) }); r.ok ? load() : toast("Login failed", true); }
  async function save() { setBusy(true); const r = await fetch("/api/admin/content", { method: "PUT", body: JSON.stringify(c) }); if (r.ok) { setC(await r.json()); toast("Saved successfully. Live on the website now."); } else toast("Failed to save. Please try again.", true); setBusy(false); }
  async function act(id: string, action: string) { const r = await fetch("/api/admin/reviews", { method: "PATCH", body: JSON.stringify({ id, action }) }); toast(r.ok ? "Review updated." : "Failed. Try again.", !r.ok); load(); }
  async function del(url: string, msg: string) { if (!confirm(msg)) return; const r = await fetch(url, { method: "DELETE" }); toast(r.ok ? "Deleted." : "Failed to delete.", !r.ok); load(); }
  if (auth === null) return <main className="wrap">Loading…</main>;
  if (!auth) return (<main className="wrap"><h1>Admin</h1><form onSubmit={login} className="glass"><label>Password<input type="password" value={pw} onChange={e => setPw(e.target.value)} /></label><button className="btn">Log in</button></form>{t && <div className="toast err" role="alert">{t.m}</div>}</main>);
  const works = c.portfolio.works, pend = rv.reviews.filter((r: any) => r.status === "pending").length;
  const saveable = ![0, 6].includes(tab);
  return (<Ctx.Provider value={{ c, set, toast }}><div className="adm">
    <aside className="side" aria-label="Admin navigation"><b style={{ display: "block", padding: 12 }}>CMS</b>
      {TABS.map((n, i) => <button key={n} className={tab === i ? "on" : ""} onClick={() => setTab(i)}>{n}{i === 6 && pend ? ` (${pend})` : ""}</button>)}
      <hr /><a href="/" target="_blank" rel="noopener">View Website ↗</a><button onClick={async () => { await fetch("/api/admin/logout", { method: "POST" }); location.reload(); }}>Logout</button></aside>
    <main className="admain"><h1>{TABS[tab]}</h1>
      {saveable && <div className="savebar"><a className="btn ghost" href="/" target="_blank" rel="noopener">Preview Site</a><button className="btn" onClick={save} disabled={busy}>{busy ? "Saving…" : "Save & Publish"}</button></div>}
      {tab === 0 && <><div className="statg">{[["Portfolio videos", works.length], ["Published", works.filter((w: any) => w.status === "published").length], ["Drafts", works.filter((w: any) => w.status === "draft").length], ["Services", c.services.svc.length], ["Pending reviews", pend], ["Approved reviews", rv.count], ["Average rating", rv.average || "—"], ["Messages", msgs.length]].map(([k, v]) => <div key={k as string} className="glass"><small>{k}</small><br /><b>{v}</b></div>)}</div>
        <div className="row" style={{ margin: "16px 0" }}><button className="btn" onClick={() => setTab(5)}>+ Add Portfolio Video</button><button className="btn" onClick={() => setTab(4)}>+ Add Service</button><button className="btn ghost" onClick={() => setTab(1)}>Edit Profile</button><button className="btn ghost" onClick={() => setTab(7)}>Edit Contact</button><button className="btn ghost" onClick={() => setTab(6)}>Manage Reviews</button></div>
        <h2>Contact messages</h2>{msgs.length === 0 && <p className="muted">No messages yet.</p>}{msgs.map(m => <article key={m.id} className="glass"><b>{m.name}</b> · <a href={`mailto:${m.email}`}>{m.email}</a> · {m.service || "—"}<p>{m.message}</p><button className="btn ghost" onClick={() => del("/api/contact?id=" + m.id, "Delete this message?")}>Delete</button></article>)}</>}
      {tab === 1 && <><Media p="profile.photo" label="Profile photo" kind="image" /><Media p="profile.logo" label="Logo (optional)" kind="image" /><F p="profile.name" label="Name" /><F p="profile.title" label="Professional title" /><F p="profile.tagline" label="Tagline" /><F p="profile.bio" label="Bio" area /><F p="profile.availability" label="Availability status" /></>}
      {tab === 2 && <><F p="hero.eyebrow" label="Eyebrow" /><F p="hero.headline" label="Headline" /><F p="hero.headlineAccent" label="Headline (highlighted part)" /><F p="hero.sub" label="Subheadline" /><F p="hero.desc" label="Description" area />
        <F p="hero.cta1Text" label="Primary button text" /><F p="hero.cta1Url" label="Primary button URL" /><F p="hero.cta2Text" label="Secondary button text" /><F p="hero.cta2Url" label="Secondary button URL" />
        <h3>Stat cards</h3><List p="hero.stats" make={() => ({ k: "", v: "" })} title={i => i.v || "Stat"}>{b => <><F p={b + ".v"} label="Top label / value" /><F p={b + ".k"} label="Text" /></>}</List></>}
      {tab === 3 && <><Chk p="intro.published" label="Published" /><F p="intro.heading" label="Section heading" /><F p="intro.title" label="Video title" /><F p="intro.desc" label="Description" area /><Media p="intro.video" label="Intro video" kind="video" /><Media p="intro.thumb" label="Thumbnail" kind="image" /><Chk p="intro.autoplay" label="Autoplay (muted loop)" /><Chk p="intro.controls" label="Show controls" /><Chk p="intro.muted" label="Muted" /></>}
      {tab === 4 && <><F p="services.heading" label="Section heading" /><F p="services.desc" label="Section description" area />
        <List p="services.svc" make={() => ({ title: "New service", icon: "✨", desc: "", tags: "", price: "", featured: false, published: true })} title={i => `${i.icon} ${i.title}${i.published ? "" : " (draft)"}`}>{b => <><F p={b + ".title"} label="Title" /><F p={b + ".icon"} label="Icon (emoji)" /><F p={b + ".desc"} label="Description" area /><F p={b + ".tags"} label="Tags (comma separated)" /><F p={b + ".price"} label="Starting price (optional)" /><Chk p={b + ".featured"} label="Featured" /><Chk p={b + ".published"} label="Published" /></>}</List></>}
      {tab === 5 && <><F p="portfolio.heading" label="Section label" /><F p="portfolio.desc" label="Section heading" /><F p="portfolio.allLabel" label="“All” filter label" /><F p="portfolio.empty" label="Empty-state text" /><F p="portfolio.watchLabel" label="Button label" />
        <h3>Videos (order here = order on website)</h3><List p="portfolio.works" make={() => ({ title: "", desc: "", client: "", category: "Other", tags: "", featured: false, status: "draft", video: "", thumb: "", beforeVideo: "", afterVideo: "" })} title={i => `${i.title || "Untitled"} — ${i.status}`}>
          {b => <><F p={b + ".title"} label="Title" /><F p={b + ".client"} label="Client / company" /><Sel p={b + ".category"} label="Category" opts={CATS} /><F p={b + ".desc"} label="Description" area /><F p={b + ".tags"} label="Tags (comma separated)" /><Sel p={b + ".status"} label="Status" opts={["draft", "published", "hidden"]} /><Chk p={b + ".featured"} label="Featured" />
            <Media p={b + ".video"} label="Video" kind="video" /><Media p={b + ".thumb"} label="Thumbnail" kind="image" /><Media p={b + ".beforeVideo"} label="Before video (optional)" kind="video" /><Media p={b + ".afterVideo"} label="After video (optional)" kind="video" /></>}</List></>}
      {tab === 6 && <><p>Approved: {rv.count} · Average: {rv.average}★ · Pending: {pend}</p>{rv.reviews.map((r: any) => <article key={r.id} className="glass"><b>{r.name}</b> {r.company && `· ${r.company}`} · {"★".repeat(r.rating)} · <em>{r.status}</em>{r.verified && " ✔"}{r.featured && " ⭐"}<p>{r.text}</p>
        <div className="row">{["approve", "reject", "verify", "feature"].map(a => <button key={a} className="btn ghost" onClick={() => act(r.id, a)}>{a}</button>)}<button className="btn ghost" onClick={() => del("/api/admin/reviews?id=" + r.id, "Delete this review permanently?")}>Delete</button></div></article>)}
        <h2>Section text</h2><div className="savebar"><button className="btn" onClick={save} disabled={busy}>Save text</button></div><F p="reviews.heading" label="Heading" /><F p="reviews.desc" label="Description" area /><F p="reviews.empty" label="Empty text" /><F p="reviews.formTitle" label="Form title" /><F p="reviews.submitText" label="Submit button" /></>}
      {tab === 7 && <><F p="contact.heading" label="Heading" /><F p="contact.desc" label="Description" area /><F p="contact.email" label="Email" /><F p="contact.whatsapp" label="WhatsApp number (digits with country code, e.g. 916303002932)" /><F p="contact.location" label="Location" /><F p="contact.emailCta" label="Email CTA" /><F p="contact.waCta" label="WhatsApp CTA" />
        <F p="contact.formHeading" label="Form heading" /><F p="contact.lName" label="Name label" /><F p="contact.lEmail" label="Email label" /><F p="contact.lService" label="Service label" /><F p="contact.servicePlaceholder" label="Service placeholder" /><F p="contact.lMsg" label="Message label" /><F p="contact.submit" label="Submit button text" /><F p="contact.success" label="Success message" /></>}
      {tab === 8 && <List p="social.slinks" make={() => ({ platform: "", url: "", enabled: true })} title={i => `${i.platform || "New"}${i.enabled ? "" : " (off)"}`}>{b => <><F p={b + ".platform"} label="Platform" /><F p={b + ".url"} label="URL" /><Chk p={b + ".enabled"} label="Show publicly" /></>}</List>}
      {tab === 9 && <><F p="footer.desc" label="Description" area /><F p="footer.copyright" label="Copyright text" /><F p="footer.cta" label="CTA text" /><F p="footer.ctaUrl" label="CTA URL" /><h3>Footer links</h3><List p="footer.flinks" make={() => ({ label: "", url: "" })} title={i => i.label || "Link"}>{b => <><F p={b + ".label"} label="Label" /><F p={b + ".url"} label="URL" /></>}</List></>}
      {tab === 10 && <><F p="settings.siteTitle" label="Site title (SEO)" /><F p="settings.metaDesc" label="Meta description" area /><F p="settings.navHome" label="Nav: Home" /><F p="settings.navWork" label="Nav: Work" /><F p="settings.navReviews" label="Nav: Reviews" /><F p="settings.navContact" label="Nav: Contact" /><F p="settings.navCta" label="Nav button" />
        <Chk p="settings.waEnabled" label="Show floating WhatsApp button" /><F p="settings.waTooltip" label="WhatsApp tooltip" /><Sel p="settings.waPos" label="WhatsApp button position" opts={["left", "right"]} /></>}
    </main>{t && <div className={"toast" + (t.e ? " err" : "")} role="status">{t.m}</div>}</div></Ctx.Provider>);
}
